### ISSUE TITLE
Avoid duplicate generation of side exits

### ISSUE THREAD

**Issue by XrXr** [Shopify/yjit#117]
gen_send_general() generates the same side exit twice:

https://github.com/Shopify/yjit/blob/d47f79982375980a4e7ae71d0c5ef6a2be982ba6/yjit_codegen.c#L2963
https://github.com/Shopify/yjit/blob/d47f79982375980a4e7ae71d0c5ef6a2be982ba6/yjit_codegen.c#L2455

We should probably save the side exit code pointer on `jitstate_t` to avoid this duplication. This caching could be done because we also generate side exits with the entry ctx_t for the instruction we compile. On my fine-grained fallback branch, side exits become falling back to the interpreter for one bytecode, and generating duplicates will use more memory.

**Comment by maximecb** [comment]
I agree that we can do a better job here in terms of space efficiency. If I understand correctly, you're suggesting caching the side-exit code in `jitstate_t` based on the current instruction and context specified?

**Comment by XrXr** [comment]
> you're suggesting caching the side-exit code in jitstate_t based on the current instruction and context specified?

That's right. Since we always want to exit to the start of an instruction, the side exit pointer is good until it start compiling the next bytecode in the block.
