### ISSUE TITLE
Ruby to Ruby call could return to invalidated code

### ISSUE THREAD

**Issue by XrXr** [Shopify/yjit#226]
```ruby
# try with --yjit-call-threshold=2
class A
  def foo(arg)
    arg.times { A.remove_method(:bar) }
    self
  end

  def bar
    4
  end

  def use(arg)
    # two consecutive sends. When bar is removed, the return address
    # for calling it is already on foo's control frame
    foo(arg).bar
  end
end

A.new.use 0
A.new.use 0
A.new.use 1
```

We set the return address when performing a call, but by the time we return,
the code at the address could be invalidated. Unlike jumps in the code we generate, the
return address is written to the control frame then used later, so patching the code that
does the write isn't enough.

Patching the return address on the call stack requires finding all Fibers, which requires
walking over the entire heap. That's probably too inefficient.

Maybe when invalidating a block, the start of the block should become a jump to exit at
that bytecode location.

A different repro, same idea.

```ruby
class A
  Good = :ng
  def foo(arg)
    arg.times { A.const_set(:Good, :ok) }
    self
  end

  def id(arg)
    arg
  end

  def use(arg)
    # send followed by a opt_getinlinecache.
    foo(arg).id(Good)
  end
end

p A.new.use 0
p A.new.use 0
p A.new.use 1
```

**Comment by maximecb** [comment]
> Maybe when invalidating a block, the start of the block should become a jump to exit at that bytecode location.

That seems like a decent solution, but may be an issue with zero-length blocks?

Though I guess call continuation blocks (blocks we return to) are never zero-length.
