### ISSUE TITLE
Local variable type tracking too optimistic

### ISSUE THREAD

**Issue by XrXr** [Shopify/yjit#300]
Crasher for ruby/ruby@aeb344e65c35b9ce72185497c0692751a1ab53cf
```ruby
# For --yjit-call-threshold=2
puts RUBY_DESCRIPTION

def contrivance(hash, key)
  # Expect this to compile to an `opt_aref`.
  hash[key]

  # The [] call above tracks that the `hash` local has a VALUE that
  # is a heap pointer and the guard for the Kernel#itself call below
  # doesn't check that it's a heap pointer VALUE.
  #
  # As you can see from the crash, the call to rb_hash_aref() can set the
  # `hash` local, making eliding the heap object guard unsound.
  hash.itself
end

# This is similar to ->(recv, mid) { send(recv, mid).local_variable_set(...) }.
# By composing we avoid creating new Ruby frames and so sending :binding
# captures the environment of the frame that does the missing key lookup.
# We use it to capture the environment inside of `contrivance`.
send_then_wrap =
  Kernel.instance_method(:send).method(:bind_call).to_proc >>
    ->(binding) { binding.local_variable_set(:hash, false) }
special_missing = Hash.new(&send_then_wrap)

# Make YJIT speculate that it's a hash and generate code
# that calls rb_hash_aref().
contrivance({}, :warmup)
contrivance({}, :warmup)

# puts RubyVM::YJIT.disasm(method(:contrivance))

puts contrivance(special_missing, :binding)
```

Potential solution: xrxr/ruby@a865c880a00c53ba7330f15295a67f5c43dbd52a

We barely track any type info for locals anyways since we already discard them on method calls.

**Comment by XrXr** [comment]
> In the long term I'd like to be able to do something a bit more fine-grained.

Agreed. There are routines we call which perform GC allocation but can never call methods and we can keep retain type info through those. The tricky part is making sure that this assertion does not go out of date. Routines that have large call graphs are harder to analyze for these properties and start to call methods down the road. To make matters worse, these type of things are hard to catch with dynamic analysis because the supposedly newly added code path that could call Ruby methods might be unused in the test suite. Maybe we want to write custom [static analyzers](https://clang-analyzer.llvm.org/) for them.

On the other hand, I'm not sure if what I'm doing here is spec as it seems too powerful and implementation details leaky even for Ruby's general reputation. I will open a ticket upstream to start a discussion.

**Comment by eregon** [comment]
FWIW, somewhat related discussion recently: https://bugs.ruby-lang.org/issues/18461
https://github.com/ko1/debug_inspector can also access caller bindings, so if that's allowed it makes it clear a variable can be overwritten over any call, and one would need a way to "deoptimize a frame" to still assume a variable is unchanged across calls.

**Comment by eregon** [comment]
A quick thought: disallowing `local_variable_set` alone is not enough, since there is `binding.eval('hash = false')`.
So I think one would need to disallow getting bindings in any "sneaky" way to be able to assume that.
I think Proc#binding could also be problematic, and it can even be accessed from another Thread potentially.
:+1: to open a ticket to figure out on what would need to change in order to do such optimizations.
