### ISSUE TITLE
Is `jemalloc` still recommended with Ruby 3.2/ YJIT?

### ISSUE THREAD

**Issue by gjtorikian** [Shopify/yjit#311]
Hi all. One of the old school Ruby memory management "techniques" was to compile Ruby with jemalloc, rather than malloc—or at the least setting appropraite environment variables to load the lib, eg https://www.speedshop.co/2017/12/04/malloc-doubles-ruby-memory.html. 

I can't find any resources online as to whether `jemalloc` provides any additional benefits in the new YJIT world, and my understanding of how the two would (or wouldn't) benefit from each other is non-existent. 😅 . Is `jemalloc` still encouraged to use in Ruby 3.2?

Apologies if this isn't the right forum for this question!

**Comment by noahgibbs** [comment]
Hello! YJIT should be a separate issue from jemalloc. So it shouldn't affect whether you should use jemalloc. With-YJIT allocations will be essentially identical to without-YJIT allocations.

My own understanding is that jemalloc is still highly useful in Ruby 3.2.0, and so I'd expect the same to be true in 3.2.0 with YJIT.
