### ISSUE TITLE
System to gather daily performance and metrics

### ISSUE THREAD

**Issue by maximecb** [Shopify/yjit#80]
@paracycle suggested this subproject would be very useful, and potentially a good task for @noahgibbs to take on.

Your mission, should you choose to accept it, is to build a system that is able to compile nightly builds of YJIT, and gather benchmark results as well as statistics (the output of `--yjit-stats`) on a nightly basis. This also has the added side-benefit that it routinely verifies that our benchmarks and benchmarking infrastructure all work correctly.

Important aspects to consider:

1. We typically use AWS bare metal machines for performance tests because we can get much more stable benchmarking numbers. That would require being able to script the boot and shut down of a C5 machine.

2. The data needs to be stored in some kind of persistent database. Minimally this could be as simple as a YAML or JSON file (@paracycle did you have a specific idea in mind?). I like the plain YAML or JSON files idea (with files named based on a `YYYY-MM-DD.yaml` timestamp) because it's very straightforward to work with, particularly if someone else ends up extending this project later on, and doesn't require setting up a server.

3. It's desirable to store metadata such as the commit hash of both the `yjit` and `yjit-bench` repos for each run. We may also want to store the GCC compiler version string. Everything necessary so that someone could reproduce these results.

4. New benchmarks can get added over time.

5. There should be some kind of dashboard or method of viewing the data. Bonus points if this can be publicly visible from the web. This could be done through GitHub pages and statically generated HTML files. Again, open to input about how this is implemented. Self-contained, static HTML files have the advantage that we can view them without a server and send them to people.

Things we might like to plot:
- Speedup vs the interpreter on each benchmark and on average (geometric mean across benchmarks)
- YJIT coverage percentage on each benchmark over time (and arithmetic mean across benchmarks)
- Inline code size on each benchmark

Could also be interesting to compute the speed vs MJIT. Caveat that MJIT takes a lot longer to warm up, so we can't benchmark it in the same way that we benchmark YJIT. There's potential to be unfair to them (we didn't let them warm up), and also unfair to us (they eventually beat us, but we instantly warmed up, whereas they needed a minute to reach peak performance). So maybe the right thing to do would be to report perf of MJIT after 15 iterations (or however many `yjit-bench` currently uses for warmup) and also after 100 or 200 warmup iterations. I consider this piece not critical. The most important thing is tracking how YJIT improves over time and vs the interpreter IMO. However, tracking the perf vs MJIT may prove useful in convincing the Ruby core devs of the value of our work.

You can take this project at your own pace and the task can be broken into smaller pieces. I don't expect the first version to be pretty or fully-featured.

**Comment by paracycle** [comment]
> The data needs to be stored in some kind of persistent database. Minimally this could be as simple as a YAML or JSON file (@paracycle did you have a specific idea in mind?). I like the plain YAML or JSON files idea (with files named based on a YYYY-MM-DD.yaml timestamp) because it's very straightforward to work with, particularly if someone else ends up extending this project later on, and doesn't require setting up a server.

Yes, for this part, I was thinking that we could rely on our existing Shopify data pipelines, so that we don't have to think about how we store, parse, chart data. We can send all of our metrics to our datastore via Monorail and then create a dashboard in Mode for any queries we want to run on them.

**Comment by maximecb** [comment]
I don't know anything about Monorail either. It would definitely be nice to have the plain JSON as well, even if we use Monorail, just for futureproofing. My main concern with a project like this is that it should be kept easy to understand and maintainable by others. All in favor of fewer moving pieces. I agree with static renders and statically rendered graphs.

**Comment by noahgibbs** [comment]
Logistical question: some of this should pretty certainly be handled in the yjit-bench repo (e.g. simple scripts to gather stats and compare YJIT to MJIT.) Do you have an opinion on whether, e.g. Shopify-specific upload scripts also belong in the yjit-bench repo or if that wants a different repo?

I'll get started on the "run a script to collect a directory of stats" part first. Then easy to add steps like "gateway into another data system" or "run regularly/daily" or "configure an AWS instance" (if we want it to be regularly/dynamically configured rather than a single AMI somewhere.)

**Comment by maximecb** [comment]
I'd like to keep `yjit-bench` self-contained and easy to use on its own if possible. Also important to note that it's a public repo, so anything private or using non-public APIs has to go in another repo. The logic to configure the AWS instance, schedule things, get the data into some platform for analytics should probably go into a `yjit-metrics` private repo (or some other creative name).

That being said, scripts to compare against MJIT make sense in the `yjit-bench` repo. This will probably require exposing the number of warmup iterations as a command-line argument in `run_benchmarks.rb`, along with options to pass to the Ruby engine. We also currently have no script to run `--yjit-stats` on benchmarks. This should probably go in a separate script to avoid making things too messy? Ideally also dumping data as plain JSON like `run_benchmarks.rb` for consistency and simplicity.

**Comment by noahgibbs** [comment]
My current plan is to copy and strip down the current run_benchmarks script into something that can be re-used in multiple contexts: run with just the current Ruby, collect some metadata, pass back only raw results, allow using it with any Ruby.

Then a conceptually-higher-level script can collect Ruby-specific metadata and invoke the inner script, usually multiple times, and make the data more reasonably available to humans. So things like table formatting, multiple output formats and comparison across multiple Ruby versions would happen in the outer script, while "run this list of benchmarks, collect and label the raw data" would happen in the inner script.

I'll start a new repo that clones and uses yjit-bench. Easy enough to do. If anything I do winds up being useful in yjit-bench we can always copy it over.

**Comment by noahgibbs** [comment]
Sounds good. Once you see what I've written, it will probably become clearer which parts we'd like to adopt into yjit-bench and which ones we don't. Always harder to judge things in advance.

**Comment by noahgibbs** [comment]
So, I put yjit-metrics in a new repo: https://github.com/Shopify/yjit-metrics

It is definitely at a point where code review would be useful. There's no analysis and reporting yet - I'll separate that into a new PR so it doesn't mess with code review of what's currently in place. But I'd love feedback.

It should be possible to pull the repo and run basic_benchmark.rb. By default it will clone YJIT twice and yjit-bench once, run the benchmarks (all of them or whichever you specify on the command line) and generally do the same kind of thing that run_all_benchmarks does in yjit-bench. However, it will currently fail if it tries to run railsbench, which requires a separate setup step. I'm working on a PR to yjit-bench to automate railsbench setup.

yjit-metrics collects a lot more run metadata (e.g. Ruby config, benchmark parameters) and the YJIT stats where relevant. It also runs on a Mac set up with dev, not just on Linux with normal chruby. And it separates out a lot more of the reusable harness code from the code that is basically a giant glorified set of benchmark parameters (e.g. basic_benchmark.rb itself) that just specifies what Rubies, which benchmarks, etc. That should make it much easier to have a small "runner" script for checking YJIT enabled vs disabled, a different one for YJIT vs MJIT, etc.

Some small things I still need to fix:
* basic_benchmark.rb is very simple - it should clone from one YJIT repo into the other, not clone both of them individually
* there should be a setup script to do things like turn off turbo -- for a CI-type script, everything needs to be automated
* I'm mimicking yjit-bench in passing the benchmark parameters in multiple ways -- warmup iterations does not work like the other two current harness params

yjit-metrics currently uses its own harness.rb. There's no specific reason this couldn't be in yjit-bench, but there's also no reason it can't remain separate.

**Comment by maximecb** [comment]
I read the code and it looks pretty good 👍 

> It also runs on a Mac set up with dev, not just on Linux with normal chruby.

That's both good and bad. It's useful for testing, but the results you'll get will be nowhere near as stable and usable. Maybe we should print some kind of warning that accuracy of measurements will be reduced.

Some comments:
- I'm glad to see you are doing the benchmarking as in `run_benchmarks.rb` with taskset and setarch on Linux
- Nitpick but I'd rename `make_repo_with` to `clone_repo_with`.
- Not a fan of the way you inlined a script here: https://github.com/Shopify/yjit-metrics/blob/main/lib/yjit-metrics.rb#L176. It's not great for readability. Could you call an external .sh script or have the template be outside of that method?
- I'd like to see more comments here explaining what is happening with the metadata: https://github.com/Shopify/yjit-metrics/blob/main/lib/yjit-metrics.rb#L211
- If you want git to keep a repo, you can add an empty .gitignore file to it: https://github.com/Shopify/yjit-metrics/blob/main/data/.keep
  - You may also not want to version control the data directory
  - Users are likely to delete or move the directory
- It might be better if the warmup iterations was a command-line argument to `basic_benchmark.rb`: https://github.com/Shopify/yjit-metrics/blob/main/basic_benchmark.rb#L25

**Comment by noahgibbs** [comment]
I've added that Mac warning. The template file will probably happen tomorrow.

**Comment by noahgibbs** [comment]
Also: we weren't sure early on how much of this code could be shared outside Shopify. As you can see, nearly all of this is currently safe to mention outside Shopify. There's one ugly hack in the script to source chruby in a nonstandard location that is harmless but unsightly for non-Shopifolk. I talked to the internal tools team, and there's really not a good way around it.

But essentially all current code seems to me to contain nothing we'd want to keep secret and some things we'd prefer to make public - benchmarking harnesses in particular often merit outside peer review.

We could also move the benchmarking harness code (lib/yjit-metrics.rb, metrics-harness/harness.rb) into yjit-bench and keep yjit-metrics Shopify-only, especially if we're going to put a Shopify-specific data scraper/uploader in there.

But that's a longer-term question. In the mean time, this setup is fine and I'll keep doing it like this.

**Comment by maximecb** [comment]
OTOH if you end up using internal Shopify tools for tracking results over time, we may not want to make the code that interfaces with that public. This code is for our own use, so there's no real need to make the repo public IMO, at least not yet. We could eventually backport your harness and benchmark runner into `yjit-bench` once it's more mature as you say. You're definitely free to tell people outside the organization what you are working on and to publicly discuss this project.

With respect to the internal Shopify data pipeline and internal tools, we can talk about it, I'm open to multiple options. On the one hand I can appreciate that other Shopifolk want us to dogfood their code. On the other hand I generally prefer using well-known, standard open source tools if there are any, and plotting graphs using plain old HTML and SVG is actually not that hard.

**Comment by noahgibbs** [comment]
At this point, further development on this is occurring in https://github.com/Shopify/yjit-metrics so I'll close this issue here.
