### ISSUE TITLE
Construct to assert that a method never exited to the interpreter

### ISSUE THREAD

**Issue by maximecb** [Shopify/yjit#98]
It looks like we could really use a way to verify that Ruby methods never abnormally exit to the interpreter. This would help us write more rigorous tests. At the moment, we semi-frequently run into cases where we write test code, and it appears to behave correctly, but in fact, we're side-exiting to the interpreter early, and never running the code we want to test in the JIT. This is a silent failure.

We already store an array of blocks per iseq. I think that we could also store a one-bit flag for each iseq. In debug mode, when taking an "abnormal" side-exit, we would set this flag to 1.

One caveat here is that there are legitimate reasons to side-exit that are not a "failure" on the JIT's part. For example, when we do interrupt checks, we infrequently exit to the interpreter to handle those. AFAIK, during tests, provided there are no ractors and we don't allocate anything, this should not happen, so we should still be able to write functions in a way that we know they won't side-exit, but @XrXr your opinion is welcome.

Syntax idea (open to alternatives too):
```
YJIT.never_exited(method(:foo))
```

@jhawthorn I know this is less fun than codegen but this could be a good issue for you to work on if you're open to it. We have to be very rigorous when testing, otherwise we will all die a segfaulty death.

**Comment by jhawthorn** [comment]
> We already store an array of blocks per iseq. I think that we could also store a one-bit flag for each iseq. In debug mode, when taking an "abnormal" side-exit, we would set this flag to 1.

Alternatively could we use the existing (global) side exit counts?

**Comment by maximecb** [comment]
That seems somewhat less clean to me, because we'd have to either keep track of the old count from Ruby, or always reset it to zero. We're currently getting stats from the Shopify Core CI, so if we reset the count to zero, those stats would suddenly be no longer valid. So that leaves getting the count before, and the count after, as the other option. Maybe there's a way to wrap that in a Ruby block or something? I guess that's doable?

**Comment by jhawthorn** [comment]
Yeah, I think a Ruby block could make that ergonomic, we've done similar to record the difference in GC stats.

One thing I like about using the global side exist counts is that we can differentiate between the different types of counted side exits.

I was thinking more along the lines of adding a test similar to this one from MJIT https://github.com/ruby/ruby/blob/master/test/ruby/test_jit.rb which runs given code and has assertions on what was compiled, etc. I'll try to find some time to attempt this.

**Comment by maximecb** [comment]
Sounds good. If you want to sketch what the API could look and comment in this issue I'd be curious what you're thinking.

**Comment by maximecb** [comment]
Solved by John Hawthorne 👌
